apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  # webapp
  PORT: '${PORT}'
  REACT_APP_TTILE: '${REACT_APP_TTILE}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  POSTGRES_DB: '${POSTGRES_DB}'
  POSTGRES_DATA: '${POSTGRES_DATA}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
  HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
  HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
  HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
  HAPI_NETWORK_BASE_ACCOUNT: '${HAPI_NETWORK_BASE_ACCOUNT}'
  HAPI_NETWORK_BASE_PASSWORD: '${HAPI_NETWORK_BASE_PASSWORD}'
  HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
  HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  HAPI_CERTIFICATE_LIMIT: '${HAPI_CERTIFICATE_LIMIT}'
  HAPI_YAIPAN_ACCESS_TOKEN: '${HAPI_YAIPAN_ACCESS_TOKEN}'
  HAPI_YAIPAN_CONSTACIAS_API_ENDPOINT: '${HAPI_YAIPAN_CONSTACIAS_API_ENDPOINT}'
  HAPI_PUBLIC_RE_CAPTCHA_KEY: '${HAPI_PUBLIC_RE_CAPTCHA_KEY}'
  HAPI_RE_CAPTCHA_PROJECT_ID: '${HAPI_RE_CAPTCHA_PROJECT_ID}'
  GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_APPLICATION_CREDENTIALS}'
  HAPI_MAIL_HOST: '${HAPI_MAIL_HOST}'
  HAPI_MAIL_PORT: '${HAPI_MAIL_PORT}'
  HAPI_MAIL_USER: '${HAPI_MAIL_USER}'
  HAPI_MAIL_PASSWORD: '${HAPI_MAIL_PASSWORD}'
  HAPI_URL_ORGANIZATION: '${HAPI_URL_ORGANIZATION}'
  HAPI_ORGANIZATION_IMAGE: '${HAPI_ORGANIZATION_IMAGE}'
  HAPI_FACEBOOK_LINK: '${HAPI_FACEBOOK_LINK}'
  HAPI_TWITTER_LINK: '${HAPI_TWITTER_LINK}'
  HAPI_INSTAGRAM_LINK: '${HAPI_INSTAGRAM_LINK}'
  HAPI_YOUTUBE_LINK: '${HAPI_YOUTUBE_LINK}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
